""" Kolekto configuration parsers.
"""

import pkg_resources

from confiture import Confiture
from confiture.schema import ValidationError
from confiture.schema.containers import Section, Value, List, Choice
from confiture.schema.types import String, Boolean

from .profiles.movies import Movies


class Profile(String):

    """ Type for Kolekto profiles.

    This type load know profiles using distutils entry-points.
    """

    def validate(self, value):
        value = super(Profile, self).validate(value)
        # Get the first profile to match the provided value:
        profile = next(pkg_resources.iter_entry_points('kolekto.profiles', str(value)), None)
        if profile is None:
            raise ValidationError('Unknown profile')
        return profile.name, profile.load()

    def cast(self, value):
        raise NotImplementedError()


class ViewKolektoConfig(Section):

    _meta = {'args': Value(String()),
             'unique': True,
             'repeat': (0, None)}

    pattern = List(String())


class DatasourceKolektoConfig(Section):

    _meta = {'args': Value(String()),
             'unique': True,
             'repeat': (0, None),
             'allow_unknown': True}


class ListingKolektoConfig(Section):

    _meta = {'args': Value(String()),
             'unique': True,
             'repeat': (0, None)}

    pattern = Value(String())
    order = List(String(), default=['title', 'year'])


class WebExportColumnKolektoConfig(Section):

    FILTER_CHOICES = {'input': 'input',
                      'select': 'select',
                      'multiple': 'multiple',
                      'checklist': 'checklist',
                      'none': 'none'}

    _meta = {'args': Value(String()),
             'unique': True,
             'repeat': (1, None)}

    pattern = Value(String())
    link = Value(Boolean(), default=False)
    is_date = Value(Boolean(), default=False)
    filter_type = Choice(FILTER_CHOICES, default='input')


class WebExportKolektoConfig(Section):

    _meta = {'args': Value(String()),
             'unique': True,
             'repeat': (0, None)}

    page_title = Value(String(), default='Kolekto listing')
    page_credits = Value(String(), default='Page generated by <a href="https://github.com/naps/Kolekto">Kolekto</a>')
    column = WebExportColumnKolektoConfig()


class RootKolektoConfig(Section):

    profile = Value(Profile(), default=('movies', Movies))
    view = ViewKolektoConfig()
    datasource = DatasourceKolektoConfig()
    listing = ListingKolektoConfig()
    webexport = WebExportKolektoConfig()


def parse_config(filename):
    conf = Confiture.from_filename(filename, schema=RootKolektoConfig())
    return conf.parse()
